server:
  port: ${WEB_PORT:8082}
  servlet:
    context-path: ${WEB_CONTEXT_PATH:/api/v1}

spring:
  profiles:
    active: ${SPRING_PROFILE:console-logger}

springdoc:
  swagger-ui:
    operations-sorter: method

logging:
  level:
    root: ${LOGGING_ROOT_LEVEL:INFO}
    org:
      springframework: ${SPRING_LOG_LEVEL:OFF}